[package]
name = "engine-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
any_vec = "0.15.0"
arena = { path = "../../mylibs/arena" }
smallbitvec = "2.6.0"

[profile.release]
debug = true
